#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.


echo "Build hook running"

ARCH=`go env GOARCH`
VERSION=`cat ../VERSION`
CODE_VERSION=v`strip $VERSION`

BUILD_ARGS = --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
			 --build-arg VERSION=$(CODE_VERSION) \
			 --build-arg VCS_URL=`git config --get remote.origin.url` \
		   --build-arg VCS_REF=`git rev-parse --short HEAD` \
		   --build-arg ARCH=$ARCH \
			 --build-arg FRAMEWORK_VERSION="0.10.0.post2"

docker build $(BUILD_ARGS) \
		-f Dockerfile.$ARCH_cpu \
		-t IMAGE_NAME .
