#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.


echo "Build hook running"

ARCH="amd64"
CODE_VERSION=`cat ../VERSION`

BUILD_ARGS=--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
			 --build-arg VERSION=$CODE_VERSION \
			 --build-arg VCS_URL=`git config --get remote.origin.url` \
		   --build-arg VCS_REF=`git rev-parse --short HEAD` \
		   --build-arg ARCH=$ARCH \
			 --build-arg FRAMEWORK_VERSION="0.10.0.post2"

if [[ $CACHE_TAG == *"_cpu"* ]]; then
  DOCKERFILE=Dockerfile.$ARCH_cpu
else
  DOCKERFILE=Dockerfile.$ARCH_gpu
fi

docker build $BUILD_ARGS \
		-f $DOCKERFILE \
		-t IMAGE_NAME .
